#!/bin/bash
#PBS -N test_fmm
#PBS -l mppwidth=2
#PBS -l mppnppn=24
#PBS -l walltime=0:30:00
#PBS -joe
#PBS -V
####PBS -q debug

cd ${PBS_O_WORKDIR}

aprun -n 48 -N 24 ./test_fmm_r32.x  100 2
aprun -n 48 -N 24 ./test_fmm_r32.x  200 2
aprun -n 48 -N 24 ./test_fmm_r32.x  300 2
aprun -n 48 -N 24 ./test_fmm_r32.x  400 2
aprun -n 48 -N 24 ./test_fmm_r32.x  500 2
aprun -n 48 -N 24 ./test_fmm_r32.x  600 2
aprun -n 48 -N 24 ./test_fmm_r32.x  700 2
aprun -n 48 -N 24 ./test_fmm_r32.x  800 2
aprun -n 48 -N 24 ./test_fmm_r32.x  900 2
aprun -n 48 -N 24 ./test_fmm_r32.x 1000 2
