#!/bin/bash
#PBS -N test_fmm
#PBS -l mppwidth=24
#PBS -l walltime=0:30:00
#PBS -joe
#PBS -V
####PBS -q debug

export XT_SYMMETRIC_HEAP_SIZE=1000M

cd ${PBS_O_WORKDIR}

aprun -n 24 ./test_fmm_r32.x  100 2 > fmm_n100_${PBS_JOBID}.output
aprun -n 24 ./test_fmm_r32.x  200 2 > fmm_n200_${PBS_JOBID}.output
aprun -n 24 ./test_fmm_r32.x  300 2 > fmm_n300_${PBS_JOBID}.output
aprun -n 24 ./test_fmm_r32.x  400 2 > fmm_n400_${PBS_JOBID}.output
aprun -n 24 ./test_fmm_r32.x  500 2 > fmm_n500_${PBS_JOBID}.output
aprun -n 24 ./test_fmm_r32.x  600 2 > fmm_n600_${PBS_JOBID}.output
aprun -n 24 ./test_fmm_r32.x  700 2 > fmm_n700_${PBS_JOBID}.output
aprun -n 24 ./test_fmm_r32.x  800 2 > fmm_n800_${PBS_JOBID}.output
aprun -n 24 ./test_fmm_r32.x  900 2 > fmm_n900_${PBS_JOBID}.output
aprun -n 24 ./test_fmm_r32.x 1000 2 > fmm_n1000_${PBS_JOBID}.output
